#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin.
# Build: compile src/ → lib/ with the dsh checkout's tsc.
# Requires DSH_CHECKOUT pointing at a dsh source checkout (auto-probe below).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Windows PowerShell 5.1 decodes BOM-less scripts as ANSI. A single non-ASCII
# byte in win.ps1 (e.g. a Chinese comment) makes the decoder swallow line
# breaks and the script fails at parse time. Fail the build instead.
if command -v node >/dev/null 2>&1; then
  node -e '
    const fs = require("fs");
    const buf = fs.readFileSync("scripts/win.ps1");
    let bad = 0;
    for (const byte of buf) if (byte > 127) bad++;
    if (bad > 0) {
      console.error("build: ERROR scripts/win.ps1 has " + bad + " non-ASCII byte(s);"
        + " Windows PowerShell 5.1 will corrupt a BOM-less non-ASCII script.");
      process.exit(1);
    }
    console.log("=== win.ps1 ASCII check: OK ===");
  ' || exit 1
fi

# DSH_CHECKOUT 探测：环境变量 → 常见路径（home 下 dsh-harness）
CHECKOUT="${DSH_CHECKOUT:-}"
if [ -z "$CHECKOUT" ]; then
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if [ -d "$candidate/packages" ]; then CHECKOUT="$candidate"; break; fi
  done
fi
if [ -z "$CHECKOUT" ] || [ ! -d "$CHECKOUT/packages" ]; then
  echo "build: cannot locate the dsh checkout (set DSH_CHECKOUT)" >&2
  exit 1
fi

TSC="$CHECKOUT/node_modules/.bin/tsc"
if [ ! -x "$TSC" ] && [ ! -f "$TSC.cmd" ]; then
  echo "build: tsc not found at $TSC" >&2
  exit 1
fi

link_pkg() {
  local target="$CHECKOUT/$2"
  if [ ! -e "$target" ]; then
    echo "build: dependency target missing: $target" >&2
    exit 1
  fi
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "node_modules/$1" "$target"
}

echo "=== Linking build dependencies (checkout: $CHECKOUT) ==="
mkdir -p node_modules/@deepseek-ai
node -e "const fs=require('fs');fs.rmSync('node_modules/@standard-schema',{recursive:true,force:true})"
link_pkg cordis vendor/cordis
link_pkg cosmokit vendor/cosmokit
link_pkg schemastery vendor/schemastery

# 已编译副本优先。本机的源码 checkout 常常没 build 过（无 lib/），
# 直接 junction 过去会让 tsc 报 TS2307，运行期 import 也会崩。
# 这种情况保留 node_modules 里已有的（已编译）链接不动。
link_pkg_built() {
  local name="$1" rel="$2"
  if [ -d "$CHECKOUT/$rel/lib" ]; then
    link_pkg "$name" "$rel"
  elif [ -e "node_modules/$name" ]; then
    echo "build: keep existing node_modules/$name (checkout copy has no lib/)"
  else
    echo "build: WARNING $name has no built copy available" >&2
  fi
}

link_pkg_built @deepseek-ai/dsh-tools packages/core/tools
link_pkg_built @deepseek-ai/dsh-llm packages/llm/llm
link_pkg_built @deepseek-ai/dsh-system-prompt packages/core/system-prompt
# @types/node（编译类型；checkout 自带）
link_pkg @types/node node_modules/@types/node

STD_SCHEMA=$(find "$CHECKOUT/node_modules/.pnpm" -maxdepth 1 -type d -iname '@standard-schema+spec@*' 2>/dev/null | head -1)
if [ -n "$STD_SCHEMA" ]; then
  node -e "
    const fs = require('fs');
    const path = require('path');
    fs.rmSync('node_modules/@standard-schema', { recursive: true, force: true });
    fs.mkdirSync('node_modules/@standard-schema', { recursive: true });
    fs.symlinkSync(path.resolve(process.argv[1]), path.resolve('node_modules/@standard-schema/spec'), process.platform === 'win32' ? 'junction' : 'dir');
  " "$STD_SCHEMA/node_modules/@standard-schema/spec"
fi

echo "=== Compiling src → lib ==="
"$TSC" -p tsconfig.json
echo "=== Build complete ==="
